name: CI

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    test:
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
        runs-on: ubuntu-latest
        steps:
            - name: Install Playwright browsers and dependencies
              uses: microsoft/playwright-github-action@v1
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm test
            - name: Build
              run: npm run build -w yash-design-system
